### ISSUE TITLE
[BUG] Changelogs below older beta/alpha posts only show the latest changelog

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/Website#44]
**Describe the bug**
When visiting a post page that features a changelog, the latest changelog (beta 19 at time of posting) is always shown, no matter the actual post.

**To Reproduce**
1. Go to any non-latest update post.
2. Observe the wrong changelog.

**Expected behavior**
Each article should display the changelog of the version it talks about.

**Screenshots**
![Snímek obrazovky 2022-01-23 v 14 44 07](https://user-images.githubusercontent.com/59484948/150681505-e1976a19-f144-48d7-9b1d-6b3506890f67.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Firefox 96.0.2

**Comment by TheRolfFR** [comment]
So after a little bit of investigation it seems like that when we load the changelog page, we just [load the entire main changelog](https://github.com/Compliance-Resource-Pack/Website/blob/9d4bcc4fb3f94321f439ef101290267d7af8ca11/_layouts/post.html#L139) without customization, may need more work to get only the version changelog but doable. I also noticed that @Juknum [renamed the main_changelog variable](https://github.com/Compliance-Resource-Pack/Website/commit/71913d87f80ff6b0d730f356624ed722ad7acbb9) so he knows more things than I do

**Comment by Juknum** [comment]
It is planned to remove this in the near future, once everything is implemented, a special collection will be created for packs update & another collection for changelogs, where they would be dynamically attached to the corresponding post, no more markdown file to edit & no more new commits for the website repo. But there is some more important stuff to make before..
