### ISSUE TITLE
[Bug] Mods & Modpacks thumbnails doesn't load anymore

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/Website#56]
### What happened?

It seems that the API link we used before is now broken https://addons-ecs.forgesvc.net/api/v2/ (because Curse Forge now properly made their own API), meaning that the fallback mods logo is displayed for mods & that the modpacks page **does not load at all** now; 

### To reproduce

1. Go to https://www.faithfulpack.net/modpacks or https://www.faithfulpack.net/mods
2. Open the console: see :'(

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49886317/168875410-c4e37014-e96f-415c-a5bb-552afda29ac8.png)
![image](https://user-images.githubusercontent.com/49886317/168875562-949a6d6a-fe9b-4e1a-a5aa-1f259bfaf1c3.png)

### Browser name and version

Any

### Notes

We may already have early access to the API (somewhere inside our mailbox)

**Comment by nick-1666** [comment]
WAIT CURSEFORGE HAS AN API!? DUDE COMPLYLE IS COMING BACK

**Comment by nick-1666** [comment]
also a new mod to download the latest version of faithful

**Comment by DMgaming100** [comment]
yooo complyle

**Comment by RobertRR11** [comment]
> WAIT CURSEFORGE HAS AN API!?

duh
