### ISSUE TITLE
[Bug] Mods thumbnail overflow when the image isn't square

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/Website#58]
### What happened?

Mod thumbnail can overflow when the given image isn't square

### To reproduce

1. Go to https://faithfulpack.net/mods
2. Search for `mal`
3. See the MalisisDoor mod being bugged

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49886317/169422764-adca9c37-4e78-4799-b149-325de44b7f6f.png)

### Browser name and version

any

**Comment by TheRolfFR** [comment]
Can be solved with :
```css
img:not(.img-gallery) {
  max-height: 100%;
}
```
