### ISSUE TITLE
[Bug] Mods page isn’t user friendly on mobile

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/Website#60]
### What happened?

The mods page is a bit wonky on small devices

### To reproduce

1. Open the mods page on any mobile

### Screenshot(s)

![D62BED37-9906-4424-9824-81C29CC0BCE3](https://user-images.githubusercontent.com/49886317/169688955-8ed43ed5-28e1-4515-951c-61b51f32f935.png)

### Browser name and version

- any

### Notes

Idea to fix it: the mods name, aliases and versions labels should depends on the screen size;

**Comment by TheRolfFR** [comment]
![image](https://user-images.githubusercontent.com/18086786/171272280-6377e5f6-8481-451b-b6ef-378afb9fe5c8.png)
