### ISSUE TITLE
[Bug] Can't download all 1.18.2 mods textures

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/Website#64]
### What happened?

Nothing happens when clicking on the 1.18.2 button on the https://faithfulpack.net/mods page

### To reproduce

1. Go to https://faithfulpack.net/mods
2. Click on the 1.18.2 button

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49886317/170867510-b7626dfc-1001-44d1-a49e-34f7e8552f30.png)

### Browser name and version

- Edge (latest version)

**Comment by TheRolfFR** [comment]
Could you pause on exceptions by clicking this button in sources ?
![image](https://user-images.githubusercontent.com/18086786/171032909-021c3021-9fd7-4408-806f-a00b31cce351.png)

**Comment by TheRolfFR** [comment]
This mod doesn't have a ``git_repository`` field in ``resource_pack`` field :
![image](https://user-images.githubusercontent.com/18086786/171277011-03c3db8e-ef34-44d0-b0c3-bb9bed6d8671.png)

**Comment by Juknum** [comment]
Data was effectively wrong inside the database, it's now properly working!
