### ISSUE TITLE
[Bug] Can't select any 1.18.2 mod textures

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/Website#65]
### What happened?

On the mods page, you can't select any 1.18.2 mod

### To reproduce

1. Go to https://faithfulpack.net/mods
2. Search for the 1.18.2 version
3. Try to select a mod (any)
4. Does nothing :/

### Screenshot(s)

Nothing is shown on the console

### Browser name and version

- Edge (latest)

**Comment by TheRolfFR** [comment]
Found it.

The label is missing a for attribute.

![image](https://user-images.githubusercontent.com/18086786/171031338-3c116015-3b6d-4407-b149-c5978056b196.png)

what are the commented objects ?

**Comment by TheRolfFR** [comment]
Actually because there is no repo url in #64 , ``repoURL`` is null and the label has no ``for`` attribute, so another key is better
