### ISSUE TITLE
[Bug] A lot of thumbnails aren't 16:9, despite requiring their images to be that side ratio

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/Website#69]
### What happened?

Title. It can look really bad when the image was specifically made for 16:9, but isn't displayed with that side ratio.

### To reproduce

1. Go to the Add-ons page
2. Find any add-on (Goat Horns Plus illustrates it best, since the thumbnail image has a border)
3. See that the thumbnail isn't 16:9

### Screenshot(s)

![obrazek](https://user-images.githubusercontent.com/59484948/184494379-9538c001-afc0-470a-bc16-e57d180efe53.png)

### Browser name and version

- Firefox 103.0.1

### Notes
This also applies to a lot of header images themselves.

**Comment by TheRolfFR** [comment]
Changed all the add-on thumbnails to 16/9 :
![image](https://user-images.githubusercontent.com/18086786/184530374-4b945e8e-5914-4561-93c7-8025376863fb.png)


This article from dailymotion is very cool : https://faq.dailymotion.com/hc/en-us/articles/360022841393-How-to-preserve-the-player-aspect-ratio-on-a-responsive-page

btw **nice**

**Comment by Pomi108** [comment]
Thanks for fixing this, but it still happens on the main page for the article thumbnails
![Snímek obrazovky 2022-08-14 v 11 44 30](https://user-images.githubusercontent.com/59484948/184531392-4b5ec9fd-7ff6-4f20-83f5-2552a03e7ccd.png)
