### ISSUE TITLE
[Feature] Sort add-ons by time released

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/Website#70]
### Describe the feature you'd like

There should be a way to sort the add-ons in the add-ons page by their date of creation, both newest-to-oldest and oldest-to-newest. This setting should also be the default option.

**Comment by TheRolfFR** [comment]
There is no date inside the add-on data
![image](https://user-images.githubusercontent.com/18086786/184495261-0003f664-53ba-46fa-9833-50d7b2738752.png)

**Comment by Pomi108** [comment]
Fuck.

**Comment by RobertRR11** [comment]
then we need to add that

**Comment by Pomi108** [comment]
But there should be

**Comment by RobertRR11** [comment]
I can't think of a better example, but we could just add the release time to newly submitted add-ons and then display the date (only when sorting is activated) like this, and old add-ons just displaying "unknown"

![image](https://user-images.githubusercontent.com/57044042/184495351-9dd0d82a-3989-49da-a43d-c18e8dfb9365.png)

**Comment by Pomi108** [comment]
We should also allow addon authors (and admins) to add a date to existing addons

**Comment by RobertRR11** [comment]
and that, yes

**Comment by Juknum** [comment]
> We should also allow addon authors (and admins) to add a date to existing addons

Huh, I'm okay with admins being able to modify the date, but the date should be updated only when submitted
Might also be a good idea to have other types of sorting too (a-z, z-a...)

**Comment by RobertRR11** [comment]
and maybe also adding an date of when an add-on was updated

**Comment by RobertRR11** [comment]
implemented in the rewrite
