### ISSUE TITLE
[Feature] Make the icons used on download buttons generally better

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Website#74]
### Describe the feature you'd like

Right now, if a download button on the site is named github or curseforge on the site, a special icon will appear, which is nice, but there's a few problems

- pmc, mcpedl, and modrinth aren't supported. as you're using assets from https://fontawesome.com as far as I can tell you can use the following icons for these
  - pmc: https://fontawesome.com/icons/globe?s=solid&f=classic
  - mcpedl: https://fontawesome.com/icons/cube?s=solid&f=classic
  - modrinth: https://fontawesome.com/icons/wrench-simple?s=solid&f=classic (mods already uses the sideways one)
- the name has to be an exact match currently — if any of these keywords is in the name the icon should appear
- there's no icon if none of these are present — it would be nice to have a generic download icon if none of these are present just for consistency (example at https://fontawesome.com/icons/arrow-down-to-line?s=solid&f=classic)

**Comment by Pomi108** [comment]
Tbh we should remove the curse buttons completely and just offer the database downloads (labelled simply "Download" with a ⬇️ icon). I don't get why the curse buttons are there in the first place

**Comment by 3vorp** [comment]
I think linking to alternate listings is fine just make them secondary to the DB downloads

this especially goes for projects like f64 which have a primary audience on curseforge, more traffic there is good

**Comment by Juknum** [comment]
What I would like to have is a main button (for curse) and a dropdown one with all alternative sources (GitHub, pmc...) 

Why curse as the primary download ? Because of the revenue it generate 🤷🏼‍♂️

**Comment by 3vorp** [comment]
then what's the point of the db downloads — I'd do DB first, followed by curse, then the rest in descending order of popularity/relevance

the main reason I see alternate listings being there is both as a failsafe in case something breaks and because some people might not want to download directly for whatever reason (kinda paranoid but this is the day and age of phising adf.ly links and similar, some people don't blindly download stuff off random sites and would rather use a service they know and trust)

idk just me though, I'd rather keep them since it's not all that much of a hassle to add

**Comment by 3vorp** [comment]
implemented with 89662f2fb7c57865b6c25dabce2d8e11936b71a4 and 3cf7cfb426e03c3c667d994209d20e3fc6cc0956
