### ISSUE TITLE
[Feature] Distinguish pre-releases from regular releases on the Downloads page

### ISSUE THREAD

**Issue by ShaneBeee** [Faithful-Resource-Pack/Website#78]
### Is your feature request related to a problem?

Yes.
Recently I reported the 1.19.3 pack for missing textures, not realizing this was a pre-release:
see https://github.com/Faithful-Resource-Pack/Faithful-Java-32x/issues/24

### Describe the feature you'd like

Would be lovely to see if the release was a pre-release opposed to a regular release.

**Comment by 3vorp** [comment]
the site rewrite is redoing the formatting of the download page meaning this won't really be necessary anymore under the new proposed layout (see #85 for more info)

**Comment by 3vorp** [comment]
Support has been added in https://github.com/Faithful-Resource-Pack/Website/commit/a02dc5334a8c16d425b802e1102ec3807087c924, but someone still needs to go through and re-categorize the current prereleases under the new system.

**Comment by 3vorp** [comment]
completed with 8c2dc010e982a6ee6b14a3f903d91d8fbeb34053
