### ISSUE TITLE
[Bug] Zipping doesn't work on android webview and fennec f-droid

### ISSUE THREAD

**Issue by Damaj301damaj-lol** [Faithful-Resource-Pack/Website#80]
### What happened?

I wanted to download 1.12.2 pack, and i pressed 1.12.2, let it download, and i expected zipping time to work, but it didn't work!, and i waited for too long

### To reproduce

1. Go to the site on either Android Webview/Fennec F-Droid
2. Press 1.12.2
3. And wait

### Screenshot(s)

![Screenshot_20230104-203808](https://user-images.githubusercontent.com/90093996/210627489-dda4b4cd-a31a-426b-a08b-31abea86e9f5.png)

### Browser name and version

- Fennec F-Droid
- Version 100.1.3

- Android Webview
- Version 102.0.5005.125

**Comment by Juknum** [comment]
It's a dumb question but why did you try to download the Java Modded version of the pack on mobile? 🤔

**Comment by Damaj301damaj-lol** [comment]
not quite dumb lol, i knew this question might come, but in my case i want to put it on my PC that is currently offline :D

**Comment by TheRolfFR** [comment]
1.12.2 is veeery long to pack, take between 8 and 10 minutes to pack. And I don't know if you have a good phone

**Comment by Damaj301damaj-lol** [comment]
I doubt a Snapdragon 730 with 8 GBs of ram and on "store" compression should take 8-10 minutes, anyways, will try to wait more, also why isn't the "Zipping time" working

**Comment by TheRolfFR** [comment]
Hhhmm after investigation and reading the code the developer made (it was me, Nov 28th of 2020 OUCH 🤯) I think the jslib can't generate the data because it is not supported by your browser. Have you tried with firefox or chrome?

**Comment by Damaj301damaj-lol** [comment]
> Hhhmm after investigation and reading the code the developer made (it was me, Nov 28th of 2020 OUCH 🤯) I think the jslib can't generate the data because it is not supported by your browser. Have you tried with firefox or chrome?

android webview = lightweight chrome
fennec f-droid = literally firefox but without proprietary bits :3

**Comment by Pomi108** [comment]
Firefox has proprietary bits?

**Comment by TheRolfFR** [comment]
It doesn't mean that it won't work on the real app, could you try please and get back to us?

**Comment by jornmann** [comment]
Computer user here, same issue on Firefox 108.0.1 64-bit. Running on Gentoo Linux with the following USE: `X clang hardened openh264 system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-webp -dbus -debug -eme-free -geckodriver (-gmp-autoupdate) -hwaccel -jack -libproxy -lto -pgo -pulseaudio -screencast (-selinux) -sndio -system-png (-system-python-libs) -wayland -wifi`

**Comment by TheRolfFR** [comment]
Successfully reproduced it by downloading 1.12 with no cache, causing rate limiting, not handled correctly. Added throttle to the function and I am now downloading mods one at a time to make sure it doesn't happen. Also I added a retry mechanism if it fails

**Comment by jornmann** [comment]
Works for me now, great job!

**Comment by Juknum** [comment]
@Damaj301damaj-lol did it worked for you too ?

**Comment by Damaj301damaj-lol** [comment]
Works on both fennec f-droid and android webview now!
Thanks
